### ISSUE TITLE
Research Google Maps API

### ISSUE THREAD

**Issue by KostadinovK** [NaskoVasilev/Breathe#5]

**Comment by NaskoVasilev** [comment]
> _No description provided._

Bcause google maps is paid and we currenely have no enough resources, we will use alternative api.
https://developer.tomtom.com/maps-sdk-web-js - sdk documentation
https://developer.tomtom.com/maps-sdk-web-js/functional-examples - examples

**Comment by NaskoIT** [comment]
Bcause google maps is paid and we currenely have no enough resources, we will use alternative api.
https://developer.tomtom.com/maps-sdk-web-js - sdk documentation
https://developer.tomtom.com/maps-sdk-web-js/functional-examples - examples
